
include (./CTAddCompilerFlags)
include (./CTCheckDecls)
include (./CTCheckFuncs)
include (./CTCheckHeaders)
include (./CTEnableCXX11)
include (./CTFindLibrary)
include (./CTGenerateCopyFilesCommandString)
include (./CTInit)
include (./CTObjCARCSetEnabled)
include (./CTSearchLibs)
include (./CTTargetAddLinkerFlags)
include (./CTTargetAddPackageDependencies)
